### ISSUE TITLE
Review 3

### ISSUE THREAD

**Issue by so2niko** [anogire/what-ui#1]
```js
return a.match(regexp) - b.match(regexp);
```
https://github.com/anogire/what-ui/blob/d95e719c61ebecf1f969ad0aa25a3686c40debce/20210416/app/task1.js#L6-L8
____________________
```js
let result = -1;
let sumWinner = 0; 
const isNotFinished = arr.some((sum, cur) =>{
   sumWinner  += cur;
   return !cur;
}); 
  
 if (isNotFinished) { 
   return result; 
 } 
```
https://github.com/anogire/what-ui/blob/d95e719c61ebecf1f969ad0aa25a3686c40debce/20210416/app/task2.js#L36-L43

**Comment by anogire** [comment]
fixed
