### ISSUE TITLE
Review 5

### ISSUE THREAD

**Issue by so2niko** [anogire/what-ui#2]
```js
[i, el].flat(num))
```

https://github.com/anogire/what-ui/blob/a79a9d05c4cd926734e20d785e479bef2042c534/20210420/app/task2.js#L20
__________________________
```js
return { partsWithProduct, maxProduct };



const { partsWithProduct, maxProduct } = getMaxProduct(partitions);
```

https://github.com/anogire/what-ui/blob/a79a9d05c4cd926734e20d785e479bef2042c534/20210420/app/task2.js#L39
https://github.com/anogire/what-ui/blob/a79a9d05c4cd926734e20d785e479bef2042c534/20210420/app/task2.js#L4

**Comment by anogire** [comment]
fixed
